Repository pknu-wap/2025_1_app2_BE, pull requests merged in 2025-05, with the labels that each got.

#73 !HOTFIX: Party 필드에 기본값 설정
  src/main/java/com/wap/app2/gachitayo/domain/party/Party.java
Labels: 완료, HOTFIX

#74 !HOTFIX 파티 기본값 설정
  src/main/java/com/wap/app2/gachitayo/domain/party/Party.java
Labels: HOTFIX

#80 refactor: PartyCreateRequestDto 요청 필드 변경
  src/main/java/com/wap/app2/gachitayo/dto/request/PartyCreateRequestDto.java
  src/main/java/com/wap/app2/gachitayo/service/party/PartyFacade.java
Labels: 완료, Refactor

#82 Feature/79 유저 평가 입력 추가
  build.gradle
  src/main/java/com/wap/app2/gachitayo/controller/member/MemberController.java
  src/main/java/com/wap/app2/gachitayo/controller/party/PartyController.java
  src/main/java/com/wap/app2/gachitayo/controller/review/ReviewController.java
  src/main/java/com/wap/app2/gachitayo/domain/member/Member.java
  src/main/java/com/wap/app2/gachitayo/domain/member/MemberDetails.java
  src/main/java/com/wap/app2/gachitayo/domain/party/Party.java
  src/main/java/com/wap/app2/gachitayo/domain/party/PartyMember.java
  src/main/java/com/wap/app2/gachitayo/domain/review/Review.java
  src/main/java/com/wap/app2/gachitayo/dto/request/ReviewMemberRequest.java
  src/main/java/com/wap/app2/gachitayo/error/exception/ErrorCode.java
  src/main/java/com/wap/app2/gachitayo/jwt/JWTFilter.java
  src/main/java/com/wap/app2/gachitayo/repository/member/MemberRepository.java
  src/main/java/com/wap/app2/gachitayo/repository/member/ReviewRepository.java
  src/main/java/com/wap/app2/gachitayo/repository/party/PartyMemberRepository.java
  src/main/java/com/wap/app2/gachitayo/service/auth/GoogleAuthService.java
  src/main/java/com/wap/app2/gachitayo/service/member/MemberService.java
  src/main/java/com/wap/app2/gachitayo/service/party/PartyFacade.java
  src/main/java/com/wap/app2/gachitayo/service/party/PartyMemberService.java
  src/main/java/com/wap/app2/gachitayo/service/review/ReviewService.java
  src/test/java/com/wap/app2/gachitayo/service/review/ReviewServiceTest.java
Labels: 완료

#83 Feature/81 최종 결산자 등록
  src/main/java/com/wap/app2/gachitayo/Enum/AdditionalRole.java
  src/main/java/com/wap/app2/gachitayo/controller/party/PartyController.java
  src/main/java/com/wap/app2/gachitayo/domain/party/PartyMember.java
  src/main/java/com/wap/app2/gachitayo/dto/response/PartyMemberResponseDto.java
  src/main/java/com/wap/app2/gachitayo/error/exception/ErrorCode.java
  src/main/java/com/wap/app2/gachitayo/service/party/PartyFacade.java
  src/main/java/com/wap/app2/gachitayo/service/party/PartyMemberService.java
Labels: 완료

#84 Feature/53 금액 입력 반영
  src/main/java/com/wap/app2/gachitayo/controller/party/PartyController.java
  src/main/java/com/wap/app2/gachitayo/domain/fare/Fare.java
  src/main/java/com/wap/app2/gachitayo/domain/fare/PaymentStatus.java
  src/main/java/com/wap/app2/gachitayo/domain/location/Stopover.java
  src/main/java/com/wap/app2/gachitayo/domain/party/Party.java
  src/main/java/com/wap/app2/gachitayo/dto/request/FareRequestDto.java
  src/main/java/com/wap/app2/gachitayo/dto/response/FinalPaymentStatusResponseDto.java
  src/main/java/com/wap/app2/gachitayo/dto/response/PaymentStatusResponseDto.java
  src/main/java/com/wap/app2/gachitayo/error/exception/ErrorCode.java
  src/main/java/com/wap/app2/gachitayo/repository/fare/PaymentStatusRepository.java
  src/main/java/com/wap/app2/gachitayo/repository/location/StopoverRepository.java
  src/main/java/com/wap/app2/gachitayo/repository/party/PartyRepository.java
  src/main/java/com/wap/app2/gachitayo/service/fare/FareService.java
  src/main/java/com/wap/app2/gachitayo/service/fare/PaymentStatusService.java
  src/main/java/com/wap/app2/gachitayo/service/location/StopoverFacade.java
  src/main/java/com/wap/app2/gachitayo/service/location/StopoverService.java
  src/main/java/com/wap/app2/gachitayo/service/party/PartyFacade.java
  src/main/java/com/wap/app2/gachitayo/service/party/PartyService.java
Labels: 완료

#86 Feature/85 정산 확인 반영
  src/main/java/com/wap/app2/gachitayo/controller/party/PartyController.java
  src/main/java/com/wap/app2/gachitayo/dto/request/FareConfirmRequestDto.java
  src/main/java/com/wap/app2/gachitayo/error/exception/ErrorCode.java
  src/main/java/com/wap/app2/gachitayo/repository/party/PartyMemberRepository.java
  src/main/java/com/wap/app2/gachitayo/service/fare/PaymentStatusService.java
  src/main/java/com/wap/app2/gachitayo/service/party/PartyFacade.java
  src/main/java/com/wap/app2/gachitayo/service/party/PartyMemberService.java
Labels: 완료

#90 Feature/89 내 파티 조회
  src/main/java/com/wap/app2/gachitayo/controller/party/PartyController.java
  src/main/java/com/wap/app2/gachitayo/repository/party/PartyRepository.java
  src/main/java/com/wap/app2/gachitayo/service/party/PartyFacade.java
  src/main/java/com/wap/app2/gachitayo/service/party/PartyMemberService.java
  src/main/java/com/wap/app2/gachitayo/service/party/PartyService.java
Labels: 완료

#102 Feature/97 전화번호 인증
  build.gradle
  src/main/java/com/wap/app2/gachitayo/Enum/MobileCarrier.java
  src/main/java/com/wap/app2/gachitayo/controller/auth/SmsAuthController.java
  src/main/java/com/wap/app2/gachitayo/domain/auth/ImapStoreManager.java
  src/main/java/com/wap/app2/gachitayo/domain/member/Member.java
  src/main/java/com/wap/app2/gachitayo/dto/request/RegisterRequestDto.java
  src/main/java/com/wap/app2/gachitayo/dto/request/SmsKeyVerifyRequest.java
  src/main/java/com/wap/app2/gachitayo/dto/response/SmsInfoResponse.java
  src/main/java/com/wap/app2/gachitayo/dto/response/SmsKeyResponse.java
  src/main/java/com/wap/app2/gachitayo/error/exception/ErrorCode.java
  src/main/java/com/wap/app2/gachitayo/service/auth/GoogleAuthService.java
  src/main/java/com/wap/app2/gachitayo/service/auth/SmsAuthService.java
Labels: 완료

#109 Feature/88 파티 참가 요청 실시간 알림 + REST API 구현
  build.gradle
  src/main/java/com/wap/app2/gachitayo/Enum/JoinRequestStatus.java
  src/main/java/com/wap/app2/gachitayo/Enum/PartyEventType.java
  src/main/java/com/wap/app2/gachitayo/config/SecurityConfig.java
  src/main/java/com/wap/app2/gachitayo/config/websocket/EmailPrincipal.java
  src/main/java/com/wap/app2/gachitayo/config/websocket/WebSocketAuthInterceptor.java
  src/main/java/com/wap/app2/gachitayo/config/websocket/WebSocketConfig.java
  src/main/java/com/wap/app2/gachitayo/controller/party/PartyController.java
  src/main/java/com/wap/app2/gachitayo/controller/party/PartyJoinRequestWebSocketController.java
  src/main/java/com/wap/app2/gachitayo/domain/party/PartyJoinRequest.java
  src/main/java/com/wap/app2/gachitayo/dto/request/PartyJoinRequestSocketRequestDto.java
  src/main/java/com/wap/app2/gachitayo/dto/response/PartyJoinRequestNotificationDto.java
  src/main/java/com/wap/app2/gachitayo/dto/response/PartyUpdateNotificationDto.java
  src/main/java/com/wap/app2/gachitayo/error/exception/ErrorCode.java
  src/main/java/com/wap/app2/gachitayo/jwt/JWTFilter.java
  src/main/java/com/wap/app2/gachitayo/repository/party/PartyJoinRequestRepository.java
  src/main/java/com/wap/app2/gachitayo/service/party/PartyFacade.java
  src/main/java/com/wap/app2/gachitayo/service/party/PartyJoinRequestService.java
  src/main/java/com/wap/app2/gachitayo/service/websocket/PartyJoinRequestWebSocketUtils.java
Labels: enhancement, help wanted, 완료

#111 Hotfix 웹소켓 구성 변경
  src/main/java/com/wap/app2/gachitayo/Enum/ReviewTag.java
  src/main/java/com/wap/app2/gachitayo/config/WebConfig.java
  src/main/java/com/wap/app2/gachitayo/config/websocket/WebSocketConfig.java
  src/main/java/com/wap/app2/gachitayo/controller/review/ReviewController.java
  src/main/java/com/wap/app2/gachitayo/domain/review/Review.java
  src/main/java/com/wap/app2/gachitayo/dto/request/ReviewMemberRequest.java
  src/main/java/com/wap/app2/gachitayo/dto/response/ReviewListResponse.java
  src/main/java/com/wap/app2/gachitayo/error/exception/ErrorCode.java
  src/main/java/com/wap/app2/gachitayo/service/review/ReviewService.java
Labels: HOTFIX
